services:
  database:
    image: mongo:6.0
    container_name: design_app_db
    volumes:
      - db_data:/data/db
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: design_app_backend
    ports:
      - "8001:8000"
    environment:
      - MONGODB_URL=mongodb://database:27017
      - MONGODB_DB=design_manager
    depends_on:
      - database
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://194.233.81.106:8001/api/v1
    container_name: design_app_frontend
    ports:
      - "4000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://194.233.81.106:8001/api/v1
    depends_on:
      - backend
    restart: always

volumes:
  db_data:
